app <- ShinyDriver$new("../../")
app$snapshotInit("predict_goulburn")

app$setInputs(`patch-patch_number_1` = "click")
app$setInputs(`patch-pc_woody_veg_1` = 8, wait_=FALSE, values_=FALSE)
app$setInputs(`patch-pc_midstorey_1` = 6, wait_=FALSE, values_=FALSE)
app$setInputs(`patch-noisy_miner_1` = TRUE, wait_=FALSE, values_=FALSE)
app$snapshot()
app$setInputs(`patch-choose_patch_attributes_execute` = "click")
app$setInputs(`location-fake_region_number` = "click")
app$snapshot()
