moreinfomodal <- function(){
out <- modalDialog(
  tags$div(class='subheader', tags$h2("QUICK START")),
  tags$p("This app is designed to estimate box gum grassy woodland bird species occupancy in a given spring for a single farm.",
  "To use this app select the farm's region (this is used to approximate the farm's climate).",
  "Then specify the rainfall that has occured in the 12 months up to the spring you are interested in.",
  "Next describe the box gum grassy woodland patches on the farm:",
  "first set the number of patches;",
  "then click on each of buttons to specify the woody vegetation canopy within 500m and 3km of the patch centres,",
  " whether the patch is a remnant, and whether noisy miners occupy the patch",
  "(noisy miners are easy to detect - click on the 'i' icon when describing you patch to see more information)."
  ),
  
  tags$p("Estimates of birds that occupy the farm, and the number of bird species will appear.",
         "The attributes of the farm can be changed at any time, and the estimates will update automatically.",
         "The birds estimates can be downloaded into a table, and more detail can be viewed or downloaded as a pdf report."
  ),
  
  tags$div(class='subheader', tags$h2("COMPARISONS")),
  tags$p("The figures include estimates for a reference farm.",
         "The default is a hypothetical farm with a single remnant patch that is occupied by noisy miners.",
         "The climate, rainfall, and woody vegetation canopy of this patch is equal to the average of our training data."
  ),
  tags$p("The reference estimates can be updated at any time using the button and checkbox at the bottom right of the app."),
         

  tags$div(class='subheader', tags$h2("HOW ARE THE ESTIMATES CALCULATED?")),
  tags$p(
    "The estimates are generated by a statistical model that",
    "estimates occupancy of 62 different bird species in remnant or planted box gum grassy woodlands (BGGW) patches.",
    "The model was trained on bird surveys conducted in spring inside remnant BGGW and planted woodland patches from 2000 to 2017.",
    "Patches were in farmland in northern Victoria, NSW and southern QLD.",
    "The model accounts for the detection difficulty of each species in these surveys, the windiness at the time of the survey, and time of day of the survey."
  ),
  tags$p("Bird species detected less in 100 or fewer surveys were not included due to a risk of overfitting the model."),
  
  tags$div(class='subheader', tags$h3("PREDICTORS OF OCCUPANCY")),
  tags$p("Many environmental factors were tested for predicting bird occupancy.",
         "The final model included the survey year,",
         "summaries of long term climate and the previous 12 months,",
         "the woody vegetation canopy within 500m and 3km of the patch center,",
         "whether the patch was a remnant,",
         "and whether noisy miners were detected at the patch that year."),
  
  tags$p("Setting the values of these factors for a farm has been simplified in the web app.",
         "Survey year did not have a strong influence on bird occupancy, we suspect due to time-varying woody vegetation canopy, ",
         "and is fixed to 2018.",
         "Long term climate is given by the centre of the selected region.",
         "The mean temperature of the previous 12 months was considered difficult for users to know, so was set to the long term average temperature.",
         "The total precipitation of the previous 12 months did influence some bird occupancy according to our model, and can be set by users of the app.",
         "The remaining climate summaries of the previous 12 months had little influence on bird occupancy and were set to the equivalent long term climate averages.",
         "For each set of occupancy estimates, the full set of environmental values used to make the estimates are given in the report that can be downloaded."),
  
  tags$div(class='subheader', tags$h3("FURTHER DETAILS")),
  tags$p("A manuscript for scientific publication is under development.",
         "This work was partly funded by the Meat and Livestock Association, and in the future a public report will be available."),
  
  tags$div(class='subheader', tags$h3("QUESTIONS AND BUGS")),
  tags$p("For questions, help and bugs, please email Kassel at Kassel.Hingee@anu.edu.au"),
  title = "More Help",
  easyClose = TRUE,
  fade = TRUE
)
return(out)
}
# print(moreinfomodal(), browse = TRUE)
