aboutModalDialog <- function(){
tags$div(class="modal fade",
         id="aboutModal",
         tabindex="-1",
         "aria-labelledby"="aboutModal",
         "aria-hidden"="true",
  tags$div(class = "modal-dialog modal-fullscreen",
    tags$div(class = "modal-content",
      tags$div(class = "modal-header",
        tags$h2("About", appname)
        ),
      tags$div(class = "modal-body",
        aboutcontent()
        ),
      modalfooter_bigback()
    )
  )
)
}

aboutcontent <- function(){
	tagList(
  tags$p(appname, "This app estimates which bird species are likely to be in your farm's Box Gum Grassy Woodland (including plantings) in spring.",
	 "It estimates occupancy for 60 woodland bird species, including five of conservation concern:",
	"Brown Treecreeper, Diamond Firetail, Dusky Woodswallow, Grey-crowned Babbler, and Superb Parrot."),
  tags$p(tags$em("Use this app to:"), "Estimate birds that live on your farm, create a report, and see how it compares to the birds you've seen."),
  tags$p(tags$em("Also use this app to:"), "Estimate, and compare, which birds might live on your farm under different scenarios:",
	 tags$ul(
            tags$li("convert part of a paddock into new woodland"),
            tags$li("build a new shelterbelt"),
            tags$li("remove Box Gum Grassy Woodland"),
	    tags$li("dissuade Noisy Miners, which are often aggressive towards other birds, from living in your woodland patches"),
	    tags$li("have a wetter year"),
	    tags$li("and more")
	    )
	 ),
  tags$p(
         tags$em("More details on estimates:"),
	 "See estimates for all species and some photos by",
	 "clicking",
          actionButton_notdfl("moredetailfake", "View More Detail", class = "download_badge"),
	 "or downloading a",
          actionButton_notdfl("downloadreportfake", "Report", class = "download_badge"),
	 "You can also download a table of the estimates in '.csv' format.",
	 "Hover over a species occupancy estimate to get insight into what model predictors influence that species."
        ),
  tags$div(class='subheader', tags$h2("HOW ARE THE ESTIMATES CALCULATED?")),
  tags$p(
    "The estimates are generated by a statistical model",
    linknewtab(href = "https://doi.org/10.1002/ecy.2754",
	       "[Tobler et al. 2019]"),
    "that",
    "estimates occupancy of 62 different bird species in remnant or planted Box Gum Grassy Woodland patches.",
    "The model was trained on bird surveys conducted in spring inside remnant Box Gum Grassy Woodland and planted woodland patches from 2000 to 2017.",
    "Patches were in farmland in northern Victoria, NSW and southern QLD.",
    "The model accounts for the detection difficulty of each species in these surveys, the windiness at the time of the survey, and time of day of the survey."
  ),
  tags$p("Bird species detected less in 100 or fewer surveys were not included due to a risk of overfitting the model."),

  tags$div(class='subheader', tags$h3("PREDICTORS OF OCCUPANCY")),
  tags$p("Many environmental factors were tested for predicting bird occupancy.",
         "The final model included the survey year,",
         "summaries of long term climate and the previous 12 months,",
         "the woody vegetation canopy within 500m and 3km of the patch center,",
         "whether the patch was a remnant,",
         "and whether noisy miners were detected at the patch that year."),
  
  tags$p("Setting the values of these factors for a farm has been simplified in the web app.",
         "Survey year did not have a strong influence on bird occupancy, we suspect due to time-varying woody vegetation canopy, ",
         "and is fixed to 2018.",
         "Long term climate is given by the centre of the selected region.",
         "The mean temperature of the previous 12 months was considered difficult for users to know, so was set to the long term average temperature.",
         "The total precipitation of the previous 12 months did influence some bird occupancy according to our model, and can be set by users of the app.",
         "The remaining climate-like summaries of the previous 12 months had little influence on bird occupancy and were set to mean of our data.",
         "For each set of occupancy estimates, the full set of environmental values used to make the estimates are given in the report that can be downloaded."),
  tags$div(class='subheader', tags$h3("FURTHER DETAILS")),
  tags$p("A manuscript for scientific publication is under development.",
         "This work was partly funded by the Meat and Livestock Association, and in the future a public report will be available.",
	 tags$br(),
	 "The app was developed using", linknewtab(href = "https://shiny.rstudio.com/", "shiny"), "in",
	 linknewtab(href = "https://www.r-project.org/","R.")
	 )
  )
}
htmltools::browsable(aboutcontent()) 
