aboutModalDialog <- function(){
tags$div(class="modal fade",
         id="aboutModal",
         tabindex="-1",
         "aria-labelledby"="aboutModal",
         "aria-hidden"="true",
  tags$div(class = "modal-dialog modal-fullscreen",
    tags$div(class = "modal-content",
      tags$div(class = "modal-header",
        tags$h2("About", appname)
        ),
      tags$div(class = "modal-body",
        aboutcontent()
        ),
      modalfooter_bigback()
    )
  )
)
}

aboutcontent <- function(){
	tagList(
  tags$p(appname, "is a free new webtool for estimating the primarily native bird biodiversity within the NSW South Western Slopes bioregion, which is roughly the lower inland slopes of the Great Dividing Range, from Benalla in Victoria to Dubbo in NSW.",
	 appname, "estimates the chance of occupancy", tags$em("(Occupancy Probability)"), "in remnant Box Gum Grassy Woodlands or planted woodlands in spring for 60 of the most commonly encountered bird species.",
	 "Five species of conservation concern are included in these estimates: Brown Treecreepers, Diamond Firetail, Dusky Woodswallow, Grey-crowned Babbler and Superb Parrot.",
	 appname, "also includes visualisations, data exports and reports for printing.",
	 "Estimates by", appname, "have the potential to describe bird biodiversity dividends from some management actions.",
	 "It is underpinned by a large multi-species statistical model fitted to 17 years of empirical data."
	 ),

  tags$p("Box Gum Grassy Woodlands are ..."),
  
  tags$p(tags$em("Use this app to:"), "Estimate birds that live on your farm, create a report, and see how it compares to the birds you've seen."),
  tags$p(tags$em("Also use this app to:"), "Estimate, and compare, which birds might live on your farm under different scenarios:",
	 tags$ul(
            tags$li("convert part of a paddock into new woodland"),
            tags$li("build a new shelterbelt"),
            tags$li("remove Box Gum Grassy Woodland"),
	    tags$li("dissuade Noisy Miners, which are often aggressive towards other birds, from living in your woodland patches"),
	    tags$li("have a wetter year"),
	    tags$li("and more")
	    )
	 ),

  tags$h3("The models inside", appname),
  tags$p(
    "The estimates are generated by a statistical model",
    linknewtab(href = "https://doi.org/10.1002/ecy.2754",
	       "[Tobler et al. 2019]"),
    "that",
    "estimates occupancy of 62 different bird species in remnant or planted Box Gum Grassy Woodland patches.",
    "The model was trained on bird surveys conducted in spring inside remnant Box Gum Grassy Woodland and planted woodland patches from 2000 to 2017.",
    "Patches were in farmland in northern Victoria, NSW and southern QLD.",
    "The model accounts for the detection difficulty of each species in these surveys, the windiness at the time of the survey, and time of day of the survey."
  ),
  tags$p("Bird species detected less in 100 or fewer surveys were not included due to a risk of overfitting the model."),

  tags$p("Many environmental factors were tested for predicting bird occupancy.",
         "The final model included the survey year,",
         "summaries of long term climate and the previous 12 months,",
         "the woody vegetation canopy within 500m and 3km of the patch center,",
         "whether the patch was a remnant,",
         "and whether noisy miners were detected at the patch that year."),
  
  tags$p("Setting the values of these factors for a farm has been simplified in the web app.",
         "Survey year did not have a strong influence on bird occupancy, we suspect due to time-varying woody vegetation canopy, ",
         "and is fixed to 2018.",
         "Long term climate is given by the centre of the selected region.",
         "The mean temperature of the previous 12 months was considered difficult for users to know, so was set to the long term average temperature.",
         "The total precipitation of the previous 12 months did influence some bird occupancy according to our model, and can be set by users of the app.",
         "The remaining climate-like summaries of the previous 12 months had little influence on bird occupancy and were set to mean of our data.",
         "For each set of occupancy estimates, the full set of environmental values used to make the estimates are given in the report that can be downloaded."),
  tags$div(class='subheader', tags$h3("Further Information")),
  tags$p("A manuscript for scientific publication is under development."),

  tags$div(tags$h3("Acknowledgements")),
  tags$p(appname, "was created using the input from many people at the Sustainable Farms Initiative.",
	 "David B Lindenmayer, Martin Westgate, Daniel Florance, Suzannah Macbeth and Angelina Siegrist all made substantial contributions to the content of", paste0(appname, "."),
	 "The field surveys crucial to", appname, "were conducted by numerous expert ecologists since the year 2000.",
	 "This included: Clare Crane, Daniel Florance, David Smith, Colleen O\'Malley, Mason Crane, David Smith, Eleanor Lang, Angelina Siegrist, and David B Lindenmayer.",
	 "Remotely sensed woody cover amounts were processed by Albert van Dijk."),
tags$p("This work was partly funded by the Meat and Livestock Association.",
       "Woody cover amounts can be loaded within", appname, "thanks to the ANU Centre for Water and Landscape Dynamics with technical support gratefully received from Pablo Larraondo.")
  )
}
# htmltools::browsable(aboutcontent())
