guidemodal <- function(){
tags$div(class="modal fade",
         id="guideModal",
         tabindex="-1",
         "aria-labelledby"="aboutModal",
         "aria-hidden"="true",
  tags$div(class = "modal-dialog modal-fullscreen",
    tags$div(class = "modal-content",
      tags$div(class = "modal-header",
        tags$h2("User Guide")
        ),
      tags$div(class = "modal-body",
        guidebody()
        ),
      modalfooter_bigback()
    )
  )
)
}
      
modalfooter_bigback <- function(){
  tags$div(class = "modal-footer justify-content-center style='border-top: none;'",
           tags$button(type = "button", class = "btn btn-outline-primary py-3",
                       style="width: 50%",
                       `data-dismiss` = "modal",
                       `data-bs-dismiss` = "modal", `aria-label` = "back", 
                       icon("angle-left"), "Back"),
  )
}      
      
guidebody <- function(){tagList(
  tags$div(class='subheader', tags$h2("COMPARISONS TO A REFERENCE")),
  tags$p("The reference estimates can be set any time the app has produced a set of estimates."),
         

  tags$div(class='subheader', tags$h2("HOW ARE THE ESTIMATES CALCULATED?")),
  tags$p(
    "The estimates are generated by a statistical model",
    linknewtab(href = "https://doi.org/10.1002/ecy.2754",
	       "[Tobler et al. 2019]"),
    "that",
    "estimates occupancy of 62 different bird species in remnant or planted Box Gum Grassy Woodland patches.",
    "The model was trained on bird surveys conducted in spring inside remnant Box Gum Grassy Woodland and planted woodland patches from 2000 to 2017.",
    "Patches were in farmland in northern Victoria, NSW and southern QLD.",
    "The model accounts for the detection difficulty of each species in these surveys, the windiness at the time of the survey, and time of day of the survey."
  ),
  tags$p("Bird species detected less in 100 or fewer surveys were not included due to a risk of overfitting the model."),

  tags$div(class='subheader', tags$h3("PREDICTORS OF OCCUPANCY")),
  tags$p("Many environmental factors were tested for predicting bird occupancy.",
         "The final model included the survey year,",
         "summaries of long term climate and the previous 12 months,",
         "the woody vegetation canopy within 500m and 3km of the patch center,",
         "whether the patch was a remnant,",
         "and whether noisy miners were detected at the patch that year."),
  
  tags$p("Setting the values of these factors for a farm has been simplified in the web app.",
         "Survey year did not have a strong influence on bird occupancy, we suspect due to time-varying woody vegetation canopy, ",
         "and is fixed to 2018.",
         "Long term climate is given by the centre of the selected region.",
         "The mean temperature of the previous 12 months was considered difficult for users to know, so was set to the long term average temperature.",
         "The total precipitation of the previous 12 months did influence some bird occupancy according to our model, and can be set by users of the app.",
         "The remaining climate-like summaries of the previous 12 months had little influence on bird occupancy and were set to mean of our data.",
         "For each set of occupancy estimates, the full set of environmental values used to make the estimates are given in the report that can be downloaded."),
  tags$div(class='subheader', tags$h3("WHAT IS A PATCH?")),
  patchdefn,
  tags$p("This use of the term 'patch' comes from our focus on Box Gum Grassy Woodlands and from the bird survey locations that we used."),

  tags$p(
  "In this app, a", tags$em("planted patch"), "is a patch",
  plantedpatchdefn),

  tags$div(class='subheader', tags$h3("FURTHER DETAILS")),
  tags$p("A manuscript for scientific publication is under development.",
         "This work was partly funded by the Meat and Livestock Association, and in the future a public report will be available.",
	 tags$br(),
	 "The app was developed using", linknewtab(href = "https://shiny.rstudio.com/", "shiny"), "in",
	 linknewtab(href = "https://www.r-project.org/","R.")
	 ),
  
  tags$div(class='subheader', tags$h3("QUESTIONS AND BUGS")),
  tags$p("For questions, help and bugs, please email Kassel at Kassel.Hingee@anu.edu.au")
)
}
